[workspace]
members = ["crates/chronicle-protocol", "crates/chronicle-core", "crates/chronicle-cli", "crates/chronicle-verifier"]
resolver = "2"

[workspace.package]
version = "0.1.0-dev"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
chronicle-protocol = { path = "crates/chronicle-protocol" }
chronicle-core = { path = "crates/chronicle-core" }
